site_name: PH7
site_url: http://ph7.angrybayblade.me/
repo_url: https://github.com/angrybayblade/ph7
edit_uri: blob/main/docs/
extra_css:
  - style.css
nav:
  - HTML: html.md
  - CSS: css.md
  - Django:
    - Templates: django/
    - Static: django/static.md
